# Generated by Django 4.0.5 on 2022-12-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(default='0', max_length=40, primary_key=True, serialize=False, unique=True)),
                ('a411', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a411', to='acc.account')),
                ('a412', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a412', to='acc.account')),
                ('a501', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a501', to='acc.account')),
                ('a712', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a712', to='acc.account')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subs.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('name', models.CharField(default='0', max_length=40, primary_key=True, serialize=False, unique=True)),
                ('a411', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sa411', to='acc.account')),
                ('a412', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sa412', to='acc.account')),
                ('a501', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sa501', to='acc.account')),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subs.group')),
                ('taxes', models.ManyToManyField(to='subs.tax')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_paid', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=60)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subs.subscriber')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subs.tax')),
            ],
        ),
    ]
