# Generated by Django 4.0.5 on 2022-12-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.CharField(max_length=40, unique=True)),
                ('secret', models.CharField(max_length=255)),
            ],
        ),
    ]
